spring:
  jpa:
    properties:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/technique_shop
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
springdoc:
  swagger-ui:
    path: /swag-run.html
